default_context:
  package_name: hermes_instrument
  module_name: hermes_instrument
  short_description: A Python package to process the HERMES instrument.
  author_name: Jane Doe
  author_email: jane.doe@example.com
  license: BSD 3-Clause
  project_url: https://github.com/HERMES-SOC/hermes_instrument
  github_repo: HERMES-SOC/hermes_instrument
  minimum_python_version: 3.8
  use_compiled_extensions: n
  include_example_code: y